### ISSUE TITLE
Your request contained invalid JSON: 'utf-8' codec can't decode byte...

### ISSUE THREAD

**Issue by lorenz1974** [yzwijsen/chatgpt-powershell#4]
If you user latin caharacter like "èéàùì" you receive this error:

_You: Perché?_

Invoke-RestMethod : {
  "error": {
    "message": "Your request contained invalid JSON: 'utf-8' codec can't decode byte 0xe9 in position 274: invalid continuation byte",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
In Scripts\ChatGPT.ps1:44 car:17
+ ... $response = Invoke-RestMethod -Method POST -Uri $ApiEndpoint -Headers ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Impossibile eseguire l'indicizzazione in una matrice null.
In Scripts\ChatGPT.ps1:47 car:12
+     return $response.choices[0].message.content
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

**Comment by JustBeta** [comment]
Hello, 
I have replaced:
`$response = Invoke-RestMethod -Method POST -Uri $ApiEndpoint -Headers $headers -Body (ConvertTo-Json $requestBody)`
With:
`    $jsondata = $requestBody | ConvertTo-Json -Compress`
`    $jsondata = ([System.Text.Encoding]::UTF8.GetBytes($jsondata))`
`    $response = Invoke-RestMethod -Method POST -Uri $ApiEndpoint -Headers $headers -Body ($jsondata)`

It's ok for me but not sure it's very optimized. If you have better, I am interested.

**Comment by lorenz1974** [comment]
Hi,

problem with sending information is solved.
Now I've discovered a problem in reading responses, I think is again an encoding problem.

You: **letters with accent**
AI: AI: Here are some letters with accents in various languages:

Italian
1. Ã - used in words like "cittÃ " (city) and "mangiÃ re" (to eat)
2. Ã - used in words like "caffÃ¨" (coffee) and "pÃ¨se" (peaches)
3. Ã - used in words like "cittadÃ¬na" (citizen) and "bambÃ¬no" (child)
4. Ã - used in words like "amÃ²re" (love) and "sÃ²lo" (only)
5. Ã - used in words like "virtÃ¹" (virtue) and "sÃ¹bito" (suddenly)

Spanish:
- ÃÂ - used in words like "mÃÂ¡s" (more) and "estÃÂ¡" (he/she/it is)
- ÃÂ - used in words like "bebÃÂ©" (baby) and "pÃÂ©rdida" (loss)
- ÃÂ - used in words like "mÃÂ­o" (mine) and "mÃÂ­nimo" (minimum)
- ÃÂ - used in words like "tÃÂ³xico" (toxic) and "mÃÂ³vil" (mobile)
- ÃÂ - used in words like "tÃÂº" (you) and "ÃÂºtil" (useful)

French:
- ÃÂ - used in words like "pÃÂ¢te" (dough) and "fÃÂªte" (party)
- ÃÂ - used in words like "hÃÂ´tel" (hotel) and "pÃÂ¨re" (father)
- ÃÂ - used in words like "maÃÂ®tre" (master) and "naÃÂ¯f" (naive)
- ÃÂ - used in words like "cÃÂ´tÃÂ©" (side) and "hÃÂ´pital" (hospital)
- ÃÂ - used in words like "croÃÂ»te" (crust) and "saÃÂ»le" (willow)

Portuguese:
- ÃÂ - used in words like "pÃÂ¡" (shovel) and "mÃÂ¡" (bad)
- ÃÂ - used in words like "pÃÂ©" (foot) and "vocÃÂª" (you)
- ÃÂ - used in words like "fÃÂ­sica" (physics) and "paÃÂ­s" (country)
- ÃÂ - used in words like "vÃÂ³" (grandmother) and "mÃÂ£o" (hand)
- ÃÂ - used in words like "ÃÂºltimo" (last) and "saÃÂºde" (health)

German:
- ÃÂ - used in words like "MÃÂ¤dchen" (girl) and "HÃÂ¤lfte" (half)
- ÃÂ - used in words like "MÃÂ¶bel" (furniture) and "schÃÂ¶n" (beautiful)
- ÃÂ - used in words like "MÃÂ¼tze" (hat) and "fÃÂ¼nf" (five)
- ÃÂ - used in words like "heiÃÂen" (to be called) and "FuÃÂ" (foot)

I tried to solve but I'm not able to find a right solution (may be because I do not know exactly what the problem is! :) )

**Comment by JustBeta** [comment]
for me, it'ok.
my script is saved on utf8 with bom.

i'm join my full script:
`<#`
`This script will let you have a conversation with ChatGPT.`
`It shows how to keep a history of all previous messages and feed them into the REST API in order to have an ongoing conversation.`
`#>`

`# Define API key and endpoint`
`$ApiKey = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"`
`$ApiOrganization = "org-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"`
`$ApiEndpoint = "https://api.openai.com/v1/chat/completions"`
`$model = "gpt-3.5-turbo"`
`$token = 2000`
`$temperature = 0.7`


`<#`
`System message.`
`You can use this to give the AI instructions on what to do, how to act or how to respond to future prompts.`
`Default value for ChatGPT = "You are a helpful assistant."`
`#>`
`#$AiSystemMessage = "You are a helpful assistant"`
`$AiSystemMessage = "Vous êtes un assistant utile"`

`# we use this list to store the system message and will add any user prompts and ai responses as the conversation evolves.`
`[System.Collections.Generic.List[Hashtable]]$MessageHistory = @()`

`# Clears the message history and fills it with the system message (and allows us to reset the history and start a new conversation)`
`Function Initialize-MessageHistory ($message){`
`    $script:MessageHistory.Clear()`
`    $script:MessageHistory.Add(@{"role" = "system"; "content" = $message}) | Out-Null`
`}`

`# Function to send a message to ChatGPT. (We need to pass the entire message history in each request since we're using a RESTful API)`
`function Invoke-ChatGPT ($MessageHistory) {`
 `   # Set the request headers`
 `   $headers = @{`
 `   "Content-Type" = "application/json"`
 `   "Authorization" = "Bearer $ApiKey"`
 `   #"OpenAI-Organization" = "$ApiOrganization"`
 `   }   `

`    # Set the request body`
`    $requestBody = @{`
`        "model" = $model # "gpt-3.5-turbo"`
`        "messages" = $MessageHistory`
`        "max_tokens" = $token # 2000 # Max amount of tokens the AI will respond with`
`        "temperature" = $temperature # 0.7 # Lower is more coherent and conservative, higher is more creative and diverse.`
`    }`

`    # Send the request`
`    $jsondata = $requestBody | ConvertTo-Json`
`    $jsondata = ([System.Text.Encoding]::UTF8.GetBytes($jsondata))`
`    $response = Invoke-RestMethod -Method POST -Uri $ApiEndpoint -Headers $headers -Body ($jsondata)`
`#    $response = Invoke-RestMethod -Method POST -Uri $ApiEndpoint -Headers $headers -Body (ConvertTo-Json $requestBody)`

 `   # Return the message content`
 `   return [System.Text.Encoding]::UTF8.GetString([System.Text.Encoding]::GetEncoding("iso-8859-1").GetBytes($response. Choices[0].message.content))`
`#    return $response. Choices[0].message.content`
`}`

`# Show startup text`
`Clear-Host`
`Write-Host "######################`n# ChatGPT Powershell #`n######################`n`nEnter your prompt to continue. (type 'exit' to quit or 'reset' to start a new chat)" -ForegroundColor Yellow`

`# Add system message to MessageHistory`
`Initialize-MessageHistory $AiSystemMessage`

`# Main loop`
`while ($true) {`
`    # Capture user input`
`    $userMessage = Read-Host "`nYou"`

`    # Check if user wants to exit or reset`
`    if ($userMessage -eq "exit") {`
`        break`
`    }`
`    if ($userMessage -eq "reset") {`
`        # Reset the message history so we can start with a clean slate`
`        Initialize-MessageHistory $AiSystemMessage`

`        Write-Host "Messages reset." -ForegroundColor Yellow`
`        continue`
`    }`

`    # Add new user prompt to list of messages`
`    $MessageHistory.Add(@{"role"="user"; "content"=$userMessage})`

`    # Query ChatGPT`
`    $aiResponse = Invoke-ChatGPT $MessageHistory`

`    # Show response`
`    Write-Host "AI: $aiResponse" -ForegroundColor Yellow`

`    # Add ChatGPT response to list of messages`
`    $MessageHistory.Add(@{"role"="assistant"; "content"=$aiResponse})`
`}`

for completion:
![image](https://github.com/yzwijsen/chatgpt-powershell/assets/25150896/ff80ef5d-45cb-4b9f-b028-f948b4a0e48c)

**Comment by lorenz1974** [comment]
You got it! ;)
Good also for me.

**Comment by lorenz1974** [comment]
![image](https://github.com/yzwijsen/chatgpt-powershell/assets/8041900/b8a2f5ca-8bd1-4370-a5f8-f793fcaf454e)
